const express = require('express');
const router = express.Router();
const { v4: uuidv4 } = require('uuid');
const crypto = require('crypto');
const db = require('../database/db');
const { authMiddleware, adminMiddleware } = require('../middleware/auth');

router.use(authMiddleware);
router.use(adminMiddleware);

// Generate license key
function generateLicenseKey() {
    const segments = 4;
    const segmentLength = 5;
    let key = '';

    for (let i = 0; i < segments; i++) {
        const segment = crypto.randomBytes(segmentLength)
            .toString('hex')
            .toUpperCase()
            .substring(0, segmentLength);
        key += segment;
        if (i < segments - 1) key += '-';
    }

    return key;
}

// Get all licenses
router.get('/', async (req, res) => {
    try {
        const licenses = await db.all(`
            SELECT 
                l.*,
                u.username
            FROM licenses l
            LEFT JOIN users u ON l.user_id = u.id
            ORDER BY l.created_at DESC
        `);

        res.json({
            success: true,
            licenses
        });

    } catch (error) {
        console.error('Get licenses error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to fetch licenses'
        });
    }
});

// Generate new licenses
router.post('/generate', async (req, res) => {
    try {
        const { count, subscriptionType, durationDays, maxUses } = req.body;

        if (!count || !subscriptionType || !durationDays) {
            return res.status(400).json({
                success: false,
                message: 'Count, subscription type, and duration are required'
            });
        }

        const licenses = [];

        for (let i = 0; i < parseInt(count); i++) {
            const licenseKey = generateLicenseKey();

            const result = await db.run(
                'INSERT INTO licenses (license_key, subscription_type, duration_days, max_uses) VALUES (?, ?, ?, ?)',
                [licenseKey, subscriptionType, parseInt(durationDays), maxUses || 1]
            );

            licenses.push({
                id: result.id,
                licenseKey,
                subscriptionType,
                durationDays: parseInt(durationDays)
            });
        }

        await db.run(
            'INSERT INTO activity_logs (action, details) VALUES (?, ?)',
            ['licenses_generated', `${count} ${subscriptionType} licenses generated by admin ${req.user.username}`]
        );

        res.json({
            success: true,
            message: `${count} license(s) generated successfully`,
            licenses
        });

    } catch (error) {
        console.error('Generate licenses error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to generate licenses'
        });
    }
});

// Delete license
router.delete('/:id', async (req, res) => {
    try {
        const license = await db.get('SELECT * FROM licenses WHERE id = ?', [req.params.id]);

        if (!license) {
            return res.status(404).json({
                success: false,
                message: 'License not found'
            });
        }

        await db.run('DELETE FROM licenses WHERE id = ?', [req.params.id]);

        await db.run(
            'INSERT INTO activity_logs (action, details) VALUES (?, ?)',
            ['license_deleted', `License ${license.license_key} deleted by admin ${req.user.username}`]
        );

        res.json({
            success: true,
            message: 'License deleted successfully'
        });

    } catch (error) {
        console.error('Delete license error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to delete license'
        });
    }
});

// Export licenses to CSV
router.get('/export/csv', async (req, res) => {
    try {
        const licenses = await db.all('SELECT * FROM licenses WHERE status = "unused"');

        let csv = 'License Key,Subscription Type,Duration (Days),Created At,Status\n';

        licenses.forEach(license => {
            csv += `${license.license_key},${license.subscription_type},${license.duration_days},${license.created_at},${license.status}\n`;
        });

        res.setHeader('Content-Type', 'text/csv');
        res.setHeader('Content-Disposition', 'attachment; filename=licenses.csv');
        res.send(csv);

    } catch (error) {
        console.error('Export licenses error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to export licenses'
        });
    }
});

module.exports = router;
